name: Build standalone executables
permissions:
  contents: write
on:
  release:
    types: ["published"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        os:
          - linux
          - macos
          - win
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - id: pkg
        uses: lando/pkg-action@v2
        with:
          entrypoint: bin.js
          arch: x64
          node-version: node18
          os: ${{ matrix.os }}
          options: --output "project-marconi-${{ matrix.os }}"
          upload: false
      - id: get_asset_name
        run: |
          asset_name=$(basename "${{ steps.pkg.outputs.file }}")
          echo "asset_name=$asset_name" >> "$GITHUB_OUTPUT"
      - id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: nanoufo/action-upload-artifacts-and-release-assets@main  
        with:
          path: ${{ steps.pkg.outputs.file }}
          upload-release-files: true
          release-upload-url: ${{ steps.get_release.outputs.upload_url }}