name: Build standalone executables
on:
  release:
    types: ["published"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x64
        os:
          - win
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - uses: lando/pkg-action@v2
        with:
          entrypoint: bin.js
          arch: ${{ matrix.arch }}
          node-version: node18
          os: ${{ matrix.os }}
      